In [1]:
from create_supervised_data import MyDataset
from NeuralNetwork import NeuralNetwork
import torch
import wandb

pygame 2.5.2 (SDL 2.28.3, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
dataset = torch.load("dataset.pt")

In [3]:
query = torch.tensor(
    [
        [[0, 0, 1], [1, 0, 1], [0, 1, 0]],
        [[1, 0, 0], [0, 0, 0], [1, 0, 1]],
        [[0, 1, 0], [0, 1, 0], [0, 0, 0]],
    ],
    dtype=torch.float32,
)

for e in dataset:
    # find where e[0] == query
    if torch.equal(e[0], query):
        print(e)
        break

(tensor([[[0., 0., 1.],
         [1., 0., 1.],
         [0., 1., 0.]],

        [[1., 0., 0.],
         [0., 0., 0.],
         [1., 0., 1.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 0., 0.]]]), tensor([0, 0, 1]), tensor([-3]))


In [6]:
run_path = "hojmax/bachelor/sjego076"
api = wandb.Api()
run = api.run(run_path)
file = run.file("model.pth")
file.download(replace=True)
config = run.config

net = NeuralNetwork(config=config)
net.load_state_dict(torch.load("model.pth", map_location="cpu"))
net.eval()
print("Loaded")

{'nn': {'blocks': 8, 'value_hidden': 256, 'value_stride': 1, 'hidden_stride': 1, 'policy_stride': 1, 'value_channels': 1, 'hidden_channels': 32, 'policy_channels': 2, 'value_kernel_size': 1, 'hidden_kernel_size': 3, 'policy_kernel_size': 1}, 'env': {'width': 3, 'height': 3, 'n_colors': 3}, 'eval': {'n_lookahead': 1}, 'mcts': {'c_puct': 1, 'temperature': 1, 'search_iterations': 100}, 'train': {'max_data': 4000, 'batch_size': 256, 'n_iterations': 100000000.0, 'l2_weight_reg': 0, 'learning_rate': 0.001, 'test_interval': 200, 'value_scaling': 0.5, 'batches_per_episode': 4, 'learning_rate_decay': 0.99995}}
Loaded


In [10]:
net(query.unsqueeze(0))

(tensor([[1.5181e-08, 1.1124e-08, 1.0000e+00]], grad_fn=<SoftmaxBackward0>),
 tensor([[-3.0018]], grad_fn=<AddmmBackward0>))