In [11]:
from create_supervised_data import MyDataset
from NeuralNetwork import NeuralNetwork
import torch
import wandb

In [4]:
dataset = torch.load("dataset.pt")

In [17]:
query = torch.tensor(
    [
        [[0, 0, 1], [1, 0, 1], [0, 1, 0]],
        [[1, 0, 0], [0, 0, 0], [1, 0, 1]],
        [[0, 1, 0], [0, 1, 0], [0, 0, 0]],
    ],
    dtype=torch.float32,
)

for e in dataset:
    # find where e[0] == query
    if torch.equal(e[0], query):
        print(e)
        break

(tensor([[[0., 0., 1.],
         [1., 0., 1.],
         [0., 1., 0.]],

        [[1., 0., 0.],
         [0., 0., 0.],
         [1., 0., 1.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 0., 0.]]]), tensor([0, 0, 1]), tensor([-3]))


In [14]:
run_path = "hojmax/bachelor/lfdk3eju"
api = wandb.Api()
run = api.run(run_path)
file = run.file("model.pth")
file.download(replace=True)
config = run.config

net = NeuralNetwork(config=config)
net.load_state_dict(torch.load("model.pt", map_location="cpu"))
net.eval()
print("Loaded")

Loaded


In [18]:
net(query.unsqueeze(0))

(tensor([[4.8333e-03, 1.1179e-06, 9.9517e-01]], grad_fn=<SoftmaxBackward0>),
 tensor([[-3.5389]], grad_fn=<AddmmBackward0>))